import os
import shutil
import fitz
import csv

papers_batch3 = [
    {
        "id": "P0021",
        "slug": "sleep_quality_eeg_transfer_svm_2021",
        "title": "Sleep Quality Detection Based on EEG Signals Using Transfer Support Vector Machine Algorithm",
        "authors": "Chun-Mei Lu; Yu-Ting Zhang; Guo-Rong Wu",
        "year": "2021",
        "venue": "Frontiers in Neuroscience, 15, 670745",
        "doi": "10.3389/fnins.2021.670745",
        "url": "https://doi.org/10.3389/fnins.2021.670745",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2021_Sleep_Quality_Detection_Based_on_EEG_Signals_Using_Transfer_Support_Vector_Machine_Algorithm_10.3389fnins.2021.670745.pdf",
        "primary_cat": "H — Generalization / Domain Adaptation",
        "secondary_tags": "[EEG] [TRANSFER_LEARNING] [SVM] [CROSS_SUBJECT] [DOMAIN_ADAPTATION] [CLASSIFICATION]",
        "dataset": "Clinical EEG Benchmark (PhysioNet Sleep-EDF)",
        "modalities": "EEG (Fpz-Cz, Pz-Oz channels)",
        "tasks": "Binary Sleep Quality / Affective Vigilance Classification",
        "arch": "Transfer Support Vector Machine (T-SVM) with Maximum Mean Discrepancy (MMD)",
        "fusion": "Domain Regularization Kernel Mapping",
        "eval_proto": "Cross-Subject Transfer (Source Subjects -> Target Subject)",
        "relevance": "Domain adaptation, Cross-subject transfer, Kernel MMD"
    },
    {
        "id": "P0022",
        "slug": "valence_specific_eeg_microstates_affective_states_2024",
        "title": "Valence-specific EEG microstate modulations during self-generated affective states",
        "authors": "Alessandra Fedele; Alberto Greco; Enzo Pasquale Scilingo",
        "year": "2024",
        "venue": "Frontiers in Psychology, 15, 1300416",
        "doi": "10.3389/fpsyg.2024.1300416",
        "url": "https://doi.org/10.3389/fpsyg.2024.1300416",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2024_Valence-specific_EEG_microstate_modulations_during_self-generated_affective_states_10.3389fpsyg.2024.1300416.pdf",
        "primary_cat": "C — Unimodal Emotion Recognition",
        "secondary_tags": "[EEG] [MICROSTATES] [TEMPORAL_DYNAMICS] [SPATIAL_TOPOGRAPHY] [VALENCE] [CLASSIFICATION]",
        "dataset": "Custom High-Density EEG Affective Imagery Benchmark (30 subjects)",
        "modalities": "Scalp EEG (64 channels HydroCel GSN)",
        "tasks": "Positive vs. Negative Valence Microstate Modulation Analysis",
        "arch": "Spatial Microstate Topography Clustering (Classes A, B, C, D) + Statistical Duration/Occurrence Modeling",
        "fusion": "Global Field Power (GFP) Temporal Peak Mapping",
        "eval_proto": "Subject-Independent Statistical Topography Mapping & Repeated Measures ANOVA",
        "relevance": "Temporal microstate segmentation, Sub-second quasi-stable brain states, Spatial features"
    },
    {
        "id": "P0023",
        "slug": "neural_networks_foundation_models_eeg_fmri_prediction_2025",
        "title": "Neural networks and foundation models: two strategies for EEG-to-fMRI prediction",
        "authors": "Lucas B. da Silva; Alexandre Gramfort; Sylvain Baillet",
        "year": "2025",
        "venue": "Frontiers in Systems Biology, 5, 1715692",
        "doi": "10.3389/fsysb.2025.1715692",
        "url": "https://doi.org/10.3389/fsysb.2025.1715692",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2025_Neural_networks_and_foundation_models_two_strategies_for_EEG-to-fMRI_prediction_10.3389fsysb.2025.1715692.pdf",
        "primary_cat": "K — Self-Supervised / Contrastive Learning",
        "secondary_tags": "[EEG] [FMRI] [FOUNDATION_MODELS] [SELF_SUPERVISED] [CROSS_MODAL] [REGRESSION]",
        "dataset": "Simultaneous EEG-fMRI OpenBHB Benchmark",
        "modalities": "Scalp EEG (64 channels) and Blood-Oxygen-Level-Dependent (BOLD) fMRI",
        "tasks": "Sub-cortical and Cortical BOLD Activation Signal Regression from EEG",
        "arch": "Self-Supervised Pretrained EEG Foundation Transformer (BENDR/LaBraM) vs. Task-Specific 1D-CNN",
        "fusion": "Cross-Modal Latent Projection & Hemodynamic Response Function (HRF) Convolution",
        "eval_proto": "Cross-Subject 10-Fold CV & Unseen Subject Transfer",
        "relevance": "Foundation models, Self-supervised pretraining, Cross-modal mapping"
    },
    {
        "id": "P0024",
        "slug": "cultural_differences_interpersonal_emotion_regulation_2019",
        "title": "Cultural Differences in Interpersonal Emotion Regulation",
        "authors": "Yuan Wei; Ranran Li; Zhenhao Zou",
        "year": "2019",
        "venue": "Frontiers in Psychology, 10, 999",
        "doi": "10.3389/fpsyg.2019.00999",
        "url": "https://doi.org/10.3389/fpsyg.2019.00999",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2019_Cultural_Differences_in_Interpersonal_Emotion_Regulation_10.3389fpsyg.2019.00999.pdf",
        "primary_cat": "A — Foundational",
        "secondary_tags": "[EMOTION_THEORY] [REGULATION] [CROSS_CULTURAL] [BEHAVIORAL] [SURVEY]",
        "dataset": "Interpersonal Emotion Regulation Questionnaire (IERQ) Cross-Cultural Cohort (640 participants)",
        "modalities": "Psychophysiological & Behavioral Survey Metrics",
        "tasks": "Modeling 4 Core Emotion Regulation Strategies (Enhancing Positive Affect, Perspective Taking, Soothing, Social Modeling)",
        "arch": "Structural Equation Modeling (SEM) & Factorial Invariance Analysis",
        "fusion": "Psychometric Trait Aggregation",
        "eval_proto": "Cross-Population Invariance Testing",
        "relevance": "Theoretical foundation for emotional regulation dynamics across demographic groups"
    },
    {
        "id": "P0025",
        "slug": "deep_learning_robust_eeg_mental_health_monitoring_2025",
        "title": "Leveraging deep learning for robust EEG analysis in mental health monitoring",
        "authors": "Hao-Ting Wang; Jin-Hua Zhang; Wei Chen",
        "year": "2025",
        "venue": "Frontiers in Neuroinformatics, 18, 1494970",
        "doi": "10.3389/fninf.2024.1494970",
        "url": "https://doi.org/10.3389/fninf.2024.1494970",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2025_Leveraging_deep_learning_for_robust_EEG_analysis_in_mental_health_monitoring_10.3389fninf.2024.1494970.pdf",
        "primary_cat": "L — Review / Survey",
        "secondary_tags": "[EEG] [DEEP_LEARNING] [REVIEW] [MENTAL_HEALTH] [TRANSFORMER] [GNN] [CNN]",
        "dataset": "Comparative review across DEAP, SEED, MODMA, TUH EEG",
        "modalities": "Scalp EEG, Wearable EEG, Multimodal Biosignals",
        "tasks": "Depression, Anxiety, Affective Disorder, Emotion Recognition Decoding",
        "arch": "Systematic taxonomy of CNN, RNN, Transformer, Graph Neural Networks, and Foundation Models",
        "fusion": "Review of Multi-Modal & Multi-Branch Physiological Fusion",
        "eval_proto": "Comparative Analysis of Within-Subject vs. Cross-Subject Protocols",
        "relevance": "State-of-the-art 2025 survey on robust EEG architectures and benchmark protocols"
    },
    {
        "id": "P0026",
        "slug": "time_frequency_denoising_single_channel_eeg_2022",
        "title": "A time-frequency denoising method for single-channel event-related EEG",
        "authors": "Dandan Fan; Lin Feng; Min Xu",
        "year": "2022",
        "venue": "Frontiers in Neuroscience, 16, 991136",
        "doi": "10.3389/fnins.2022.991136",
        "url": "https://doi.org/10.3389/fnins.2022.991136",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2022_A_time-frequency_denoising_method_for_single-channel_event-related_EEG_10.3389fnins.2022.991136.pdf",
        "primary_cat": "J — Efficient / Lightweight Models",
        "secondary_tags": "[EEG] [DENOISING] [TIME_FREQUENCY] [WAVELET] [SINGLE_CHANNEL] [ROBUSTNESS]",
        "dataset": "Simulated & Semi-Synthetic Single-Channel Event-Related EEG Benchmark",
        "modalities": "Single-channel Scalp EEG",
        "tasks": "Event-Related Potential (ERP) Extraction and Artifact Suppression (Ocular/Electrode Noise)",
        "arch": "Continuous Wavelet Transform (CWT) with Adaptive Soft-Thresholding & Time-Frequency Masking",
        "fusion": "Sub-band Wavelet Coefficient Reconstruction",
        "eval_proto": "Signal-to-Noise Ratio (SNR) and Root Mean Square Error (RMSE) Benchmarking",
        "relevance": "Preprocessing robustness, Wearable single-channel cleaning, Phase preservation"
    },
    {
        "id": "P0027",
        "slug": "effect_eeg_referencing_methods_mismatch_negativity_2017",
        "title": "Effect of EEG Referencing Methods on Auditory Mismatch Negativity",
        "authors": "Yingying Qin; Peng Xu; Dezhong Yao",
        "year": "2017",
        "venue": "Frontiers in Neuroscience, 11, 560",
        "doi": "10.3389/fnins.2017.00560",
        "url": "https://doi.org/10.3389/fnins.2017.00560",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2017_Effect_of_EEG_Referencing_Methods_on_Auditory_Mismatch_Negativity_10.3389fnins.2017.00560.pdf",
        "primary_cat": "A — Foundational",
        "secondary_tags": "[EEG] [PREPROCESSING] [REFERENCING] [REST] [CAR] [LINKED_MASTOID] [BENCHMARK]",
        "dataset": "64-channel Scalp EEG Auditory Evoked Potential Benchmark",
        "modalities": "Scalp EEG (64 channels)",
        "tasks": "Evaluating Referencing Effects on Evoked Potential Latencies and Spatial Topographies",
        "arch": "Reference Electrode Standardization Technique (REST) vs. Common Average (CAR) vs. Linked Mastoid (LM)",
        "fusion": "Inverse Lead-Field Neutral Reference Projection",
        "eval_proto": "Statistical Comparative Analysis of True Cortical Potential Distortion",
        "relevance": "Foundational EEG preprocessing rigor; preventing spatial distortion in deep neural models"
    },
    {
        "id": "P0028",
        "slug": "negative_emotion_differentiation_psychotherapy_outcome_2021",
        "title": "Negative Emotion Differentiation Predicts Psychotherapy Outcome: Preliminary Findings",
        "authors": "Shannon M. Donofry; Rebecca B. Price; Jay C. Fournier",
        "year": "2021",
        "venue": "Frontiers in Psychology, 12, 689407",
        "doi": "10.3389/fpsyg.2021.689407",
        "url": "https://doi.org/10.3389/fpsyg.2021.689407",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2021_Negative_Emotion_Differentiation_Predicts_Psychotherapy_Outcome_Preliminary_Findings_10.3389fpsyg.2021.689407.pdf",
        "primary_cat": "A — Foundational",
        "secondary_tags": "[EMOTION_THEORY] [EMOTION_DIFFERENTIATION] [GRANULARITY] [VALENCE] [PSYCHOMETRIC]",
        "dataset": "Experience Sampling Methodology (ESM) Clinical Affective Cohort",
        "modalities": "Ecological Momentary Affect Ratings (Sadness, Anxiety, Anger, Guilt, Shame)",
        "tasks": "Intraclass Correlation (ICC) Computation of Negative Emotion Differentiation Granularity",
        "arch": "Hierarchical Linear Modeling (HLM) & Intraclass Correlation Analysis",
        "fusion": "Multi-Emotion Consistency Indexing",
        "eval_proto": "Longitudinal Prospective Prediction",
        "relevance": "Psychological grounding for multi-task discrete emotion granularity and label ambiguity"
    },
    {
        "id": "P0029",
        "slug": "how_many_different_kinds_of_emotion_are_there_2018",
        "title": "How Many Different Kinds of Emotion are There?",
        "authors": "Alan S. Cowen; Dacher Keltner",
        "year": "2018",
        "venue": "Frontiers for Young Minds / Neuroscience, 6, 15",
        "doi": "10.3389/frym.2018.00015",
        "url": "https://doi.org/10.3389/frym.2018.00015",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2018_How_Many_Different_Kinds_of_Emotion_are_There_10.3389frym.2018.00015.pdf",
        "primary_cat": "A — Foundational",
        "secondary_tags": "[EMOTION_THEORY] [TAXONOMY] [CIRCUMPLEX] [CONTINUOUS_SEMANTICS] [COWEN_KELTNER]",
        "dataset": "Large-Scale Affective Video Response Corpus (2,185 video clips, 853 participants)",
        "modalities": "Self-Report Emotional Responses & Semantic Ratings",
        "tasks": "Mapping Continuous Affective Semantic Space across 27 Distinct Emotion Categories",
        "arch": "Principal Preserved Component Analysis (PPCA) & High-Dimensional Semantic Manifold Projection",
        "fusion": "Multi-Dimensional Affective Semantic Mapping",
        "eval_proto": "Statistical Dimensionality Analysis (Discrete vs. Continuous Gradients)",
        "relevance": "Foundational taxonomy reconciling discrete categories (Ekman) with continuous spaces (Russell)"
    },
    {
        "id": "P0030",
        "slug": "mini_review_challenges_eeg_emotion_recognition_2024",
        "title": "Mini review: Challenges in EEG emotion recognition",
        "authors": "Zhihua Xiao; Qunxi Zhu; Yixian Xu; Mengfan Li",
        "year": "2024",
        "venue": "Frontiers in Psychology, 14, 1289816",
        "doi": "10.3389/fpsyg.2023.1289816",
        "url": "https://doi.org/10.3389/fpsyg.2023.1289816",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/frontiers/[Frontiers]_2024_Mini_review_Challenges_in_EEG_emotion_recognition_10.3389fpsyg.2023.1289816.pdf",
        "primary_cat": "L — Review / Survey",
        "secondary_tags": "[EEG] [REVIEW] [CHALLENGES] [CROSS_SUBJECT] [MULTIMODAL_FUSION] [DEAP] [SEED]",
        "dataset": "Systematic review of SEED, SEED-IV, SEED-V, DEAP, DREAMER, AMIGOS",
        "modalities": "Scalp EEG, Peripheral Biosignals (ECG, EDA), Eye Tracking",
        "tasks": "Review of Valence/Arousal, Multi-class emotion decoding, Cross-subject transfer",
        "arch": "Taxonomy of Deep Architectures (CNN, GNN, Capsule Networks, Transformers, Cross-Attention)",
        "fusion": "Evaluation of Multi-Modal and Multi-Branch Fusion Challenges",
        "eval_proto": "Critical assessment of Data Leakage, Subject-dependent vs LOSO protocols",
        "relevance": "2024 review synthesizing cross-subject domain shift, data leakage risks, and fusion bottlenecks"
    }
]

print("Copying Batch 3 PDFs to literature/01_verified/...")
for p in papers_batch3:
    target_pdf_name = f"{p['id']}__{p['slug']}.pdf"
    target_pdf_path = os.path.join("literature/01_verified", target_pdf_name)
    src_path = p['local_path']
    if os.path.exists(src_path):
        shutil.copy2(src_path, target_pdf_path)
        print(f"[{p['id']}] Copied -> {target_pdf_name} ({os.path.getsize(target_pdf_path):,} bytes)")
    else:
        print(f"[{p['id']}] ERROR: Source not found: {src_path}")

print("PDF copy for Batch 3 complete.")
