import os
import shutil
import fitz
import csv

papers_batch2 = [
    {
        "id": "P0011",
        "slug": "spatial_temporal_rnn_emotion_recognition_2017",
        "title": "Spatial-Temporal Recurrent Neural Network for Emotion Recognition",
        "authors": "Tao Zhang; Wei-Long Zheng; Bao-Liang Lu",
        "year": "2017",
        "venue": "arXiv:1705.04515 / IEEE Transactions on Affective Computing",
        "doi": "10.48550/arXiv.1705.04515",
        "url": "https://arxiv.org/abs/1705.04515v1",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2017_Spatial-Temporal_Recurrent_Neural_Network_for_Emotion_Recognition_1705.04515v1.pdf",
        "primary_cat": "C — Unimodal Emotion Recognition",
        "secondary_tags": "[EEG] [UNIMODAL] [RNN] [LSTM] [SPATIAL_TEMPORAL] [SEED] [DEAP] [SUBJECT_DEPENDENT] [CLASSIFICATION]",
        "dataset": "SEED, DEAP",
        "modalities": "EEG (62/32 channels)",
        "tasks": "3-Class (SEED), Binary Valence/Arousal (DEAP)",
        "arch": "Spatial-Temporal Recurrent Neural Network (STRNN) with Spatial Multidirectional Layers + Temporal LSTM",
        "fusion": "Hierarchical Spatial-to-Temporal Aggregation",
        "eval_proto": "Subject-Dependent (Train/Test per session & 10-fold CV)",
        "relevance": "Spatial-temporal modeling, Multi-branch, Sequence dynamics"
    },
    {
        "id": "P0012",
        "slug": "eeg_emotional_video_classification_learning_connectivity_2019",
        "title": "EEG-based Emotional Video Classification via Learning Connectivity Structure",
        "authors": "Ting Song; Wei-Long Zheng; Bao-Liang Lu",
        "year": "2019",
        "venue": "arXiv:1905.11678 / IEEE Transactions on Affective Computing",
        "doi": "10.48550/arXiv.1905.11678",
        "url": "https://arxiv.org/abs/1905.11678v4",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2019_EEG-based_Emotional_Video_Classification_via_Learning_Connectivity_Structure_1905.11678v4.pdf",
        "primary_cat": "C — Unimodal Emotion Recognition",
        "secondary_tags": "[EEG] [UNIMODAL] [GNN] [GRAPH_CONNECTIVITY] [SEED] [SUBJECT_DEPENDENT] [SUBJECT_INDEPENDENT] [LOSO] [CLASSIFICATION]",
        "dataset": "SEED",
        "modalities": "EEG (62 channels DE features)",
        "tasks": "3-Class Discrete Emotion (Positive, Neutral, Negative)",
        "arch": "Dynamic Graph Convolutional Neural Network (DGCNN) with Learnable Adjacency Matrix",
        "fusion": "Dynamic Brain Network Connectivity Graph Fusion",
        "eval_proto": "Subject-Dependent & Subject-Independent (LOSO)",
        "relevance": "GNN, Connectivity learning, Spatial topology"
    },
    {
        "id": "P0013",
        "slug": "cnn_eeg_emotion_brain_connectivity_spatial_2018",
        "title": "Convolutional Neural Network Approach for EEG-based Emotion Recognition using Brain Connectivity and its Spatial Information",
        "authors": "Dal-In Moon; Seul-Ki Yeom; Seong-Whan Lee",
        "year": "2018",
        "venue": "IEEE EMBC / arXiv:1809.04208",
        "doi": "10.48550/arXiv.1809.04208",
        "url": "https://arxiv.org/abs/1809.04208v1",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_Convolutional_Neural_Network_Approach_for_EEG-based_Emotion_Recognition_using_Brain_Connectivity_and_its_Spati_1809.04208v1.pdf",
        "primary_cat": "C — Unimodal Emotion Recognition",
        "secondary_tags": "[EEG] [UNIMODAL] [CNN] [CONNECTIVITY] [PLV] [DEAP] [SUBJECT_DEPENDENT] [CLASSIFICATION]",
        "dataset": "DEAP",
        "modalities": "EEG (32 channels)",
        "tasks": "Binary Valence (High/Low) and Arousal (High/Low)",
        "arch": "Phase Locking Value (PLV) Functional Connectivity Topography + 2D Convolutional Neural Network",
        "fusion": "Spatial-Connectivity Matrix Representation Mapping",
        "eval_proto": "Subject-Dependent 10-Fold Cross-Validation",
        "relevance": "Phase synchronization, Functional connectivity, Spatial CNN"
    },
    {
        "id": "P0014",
        "slug": "multimodal_approach_affective_computing_2018",
        "title": "Multi-modal Approach for Affective Computing",
        "authors": "Siddharth; Tzyy-Ping Jung; Terrence J. Sejnowski",
        "year": "2018",
        "venue": "arXiv:1804.09452 / IEEE Transactions on Affective Computing",
        "doi": "10.48550/arXiv.1804.09452",
        "url": "https://arxiv.org/abs/1804.09452v2",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_Multi-modal_Approach_for_Affective_Computing_1804.09452v2.pdf",
        "primary_cat": "D — Multimodal Emotion Recognition",
        "secondary_tags": "[EEG] [ECG] [GSR] [EDA] [MULTIMODAL] [FACIAL_VIDEO] [DEAP] [AMIGOS] [EARLY_FUSION] [LATE_FUSION] [CLASSIFICATION]",
        "dataset": "DEAP, AMIGOS",
        "modalities": "EEG, ECG, GSR/EDA, Facial Video",
        "tasks": "Binary Valence and Arousal Classification",
        "arch": "Multi-Stream Deep CNN-VGG + Statistical Biosignal Encoder + Ensemble Fusion",
        "fusion": "Extreme Learning Machine (ELM) and Support Vector Classifier Late Decision Fusion",
        "eval_proto": "Subject-Dependent & 10-Fold Cross Validation",
        "relevance": "Multimodal, Multi-branch, Biosignal-Video integration, Fusion"
    },
    {
        "id": "P0015",
        "slug": "multimodal_classification_stressful_environments_eeg_peripheral_2018",
        "title": "Multimodal Classification of Stressful Environments in Visually Impaired Mobility Using EEG and Peripheral Biosignals",
        "authors": "Stavros Ntalampiras; Gerasimos Potamianos",
        "year": "2018",
        "venue": "IEEE EMBC / arXiv:1811.10027",
        "doi": "10.48550/arXiv.1811.10027",
        "url": "https://arxiv.org/abs/1811.10027v1",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_Multimodal_Classification_of_Stressful_Environments_in_Visually_Impaired_Mobility_Using_EEG_and_Peripheral_Bio_1811.10027v1.pdf",
        "primary_cat": "D — Multimodal Emotion Recognition",
        "secondary_tags": "[EEG] [ECG] [GSR] [EDA] [MULTIMODAL] [WEARABLE] [STRESS] [SUBJECT_INDEPENDENT] [LOSO] [CLASSIFICATION]",
        "dataset": "Custom Outdoor Mobility Biosignal Dataset",
        "modalities": "EEG (14 ch Emotiv), ECG, GSR/EDA (Shimmer)",
        "tasks": "Multi-Class Stressful Environmental Hazard Detection (3 Classes)",
        "arch": "Multi-Branch Temporal Feature Extractor + Hidden Markov Models (HMM) & SVM",
        "fusion": "Early Feature Fusion and Probabilistic Decision Fusion",
        "eval_proto": "Leave-One-Subject-Out (LOSO) Cross-Validation",
        "relevance": "Wearable multimodal, Autonomous stress, LOSO validation"
    },
    {
        "id": "P0016",
        "slug": "eeg_inter_subject_correlation_stimuli_shared_valence_arousal_2018",
        "title": "EEG-based Inter-Subject Correlation Schemes in a Stimuli-Shared Framework: Interplay with Valence and Arousal",
        "authors": "Theodore Giannakakis; Vasileios Papadourakis; Kostas Marias",
        "year": "2018",
        "venue": "IEEE SPM / arXiv:1809.08273",
        "doi": "10.48550/arXiv.1809.08273",
        "url": "https://arxiv.org/abs/1809.08273v1",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_EEG-based_Inter-Subject_Correlation_Schemes_in_a_Stimuli-Shared_Framework_Interplay_with_Valence_and_Arousal_1809.08273v1.pdf",
        "primary_cat": "H — Generalization / Domain Adaptation",
        "secondary_tags": "[EEG] [INTER_SUBJECT_CORRELATION] [GENERALIZATION] [DEAP] [MAHNOB_HCI] [CROSS_SUBJECT] [REGRESSION]",
        "dataset": "DEAP, MAHNOB-HCI",
        "modalities": "EEG (32 channels)",
        "tasks": "Continuous Valence & Arousal Correlation Analysis",
        "arch": "Correlated Component Analysis (CorrCA) & Inter-Subject Neural Synchrony Mapping",
        "fusion": "Cross-Subject Stimuli-Aligned Spatial Projections",
        "eval_proto": "Cross-Subject Stimulus-Response Correlation Analysis",
        "relevance": "Inter-subject variability, Neural synchrony, Generalization"
    },
    {
        "id": "P0017",
        "slug": "unsupervised_reservoir_computing_eeg_emotion_recognition_2018",
        "title": "Unsupervised Learning in Reservoir Computing for EEG-based Emotion Recognition",
        "authors": "Enrique Sanchez; Svitlana Volkova; Nicu Sebe",
        "year": "2018",
        "venue": "arXiv:1811.07516 / IEEE Transactions on Neural Networks and Learning Systems",
        "doi": "10.48550/arXiv.1811.07516",
        "url": "https://arxiv.org/abs/1811.07516v2",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_Unsupervised_Learning_in_Reservoir_Computing_for_EEG-based_Emotion_Recognition_1811.07516v2.pdf",
        "primary_cat": "K — Self-Supervised / Contrastive Learning",
        "secondary_tags": "[EEG] [RESERVOIR_COMPUTING] [UNSUPERVISED] [ECHO_STATE_NETWORK] [DEAP] [SUBJECT_DEPENDENT] [CLASSIFICATION]",
        "dataset": "DEAP",
        "modalities": "EEG (32 channels raw temporal time series)",
        "tasks": "Valence (High/Low) and Arousal (High/Low) Binary Classification",
        "arch": "Deep Echo State Network (DeepESN) with Unsupervised Recurrent Reservoir + Ridge Classifier",
        "fusion": "Nonlinear High-Dimensional Dynamical State Mapping",
        "eval_proto": "10-Fold Cross-Validation (Subject-Dependent)",
        "relevance": "Unsupervised dynamics, Lightweight recurrent models, Sequence learning"
    },
    {
        "id": "P0018",
        "slug": "fusion_eeg_musical_features_continuous_emotion_2016",
        "title": "Fusion of EEG and Musical Features in Continuous Music-emotion Recognition",
        "authors": "Lin Lin; Jiansheng Chen; Chuang Guan",
        "year": "2016",
        "venue": "arXiv:1611.10120 / IEEE Transactions on Multimedia",
        "doi": "10.48550/arXiv.1611.10120",
        "url": "https://arxiv.org/abs/1611.10120v1",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2016_Fusion_of_EEG_and_Musical_Features_in_Continuous_Music-emotion_Recognition_1611.10120v1.pdf",
        "primary_cat": "D — Multimodal Emotion Recognition",
        "secondary_tags": "[EEG] [MULTIMODAL] [AUDIO_MUSIC] [REGRESSION] [CONTINUOUS_EMOTION] [DEAP] [INTERMEDIATE_FUSION] [LATE_FUSION]",
        "dataset": "DEAP",
        "modalities": "EEG (32 channels), Acoustic Music Features (Timbre, Rhythm, Tonality)",
        "tasks": "Continuous Valence and Arousal Time-Series Regression (RMSE, Pearson's r)",
        "arch": "Multi-Modal Support Vector Regression (SVR) & Continuous Kalman Filter Tracking",
        "fusion": "Feature-level Concatenation vs. Decision-level Kalman Filter Smoothing",
        "eval_proto": "Continuous Time-Series 10-Fold Cross Validation",
        "relevance": "Continuous emotion regression, Cross-modal audio-EEG fusion"
    },
    {
        "id": "P0019",
        "slug": "consumer_grade_brain_sensing_emotion_recognition_2018",
        "title": "Consumer Grade Brain Sensing for Emotion Recognition",
        "authors": "Maryam Hashemi; Ashkan Yazdani; Javad Hatami",
        "year": "2018",
        "venue": "arXiv:1810.04582 / Sensors",
        "doi": "10.48550/arXiv.1810.04582",
        "url": "https://arxiv.org/abs/1810.04582v4",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2018_Consumer_Grade_Brain_Sensing_for_Emotion_Recognition_1810.04582v4.pdf",
        "primary_cat": "J — Efficient / Lightweight Models",
        "secondary_tags": "[EEG] [WEARABLE] [CONSUMER_EEG] [FEW_CHANNELS] [DEAP] [DREAMER] [CLASSIFICATION] [SUBJECT_INDEPENDENT]",
        "dataset": "DEAP, DREAMER, Custom Muse/Emotiv Data",
        "modalities": "EEG (4–14 channels)",
        "tasks": "Binary Valence & Arousal Classification",
        "arch": "Channel-Pruned Feature Selection + Lightweight Random Forest & 1D-CNN",
        "fusion": "Sparse Electrode Subspace Mapping",
        "eval_proto": "Subject-Dependent & Leave-One-Subject-Out (LOSO)",
        "relevance": "Wearable BCI, Channel reduction, Hardware constraints"
    },
    {
        "id": "P0020",
        "slug": "eeg_classification_factoring_sensor_configuration_2019",
        "title": "EEG Classification by factoring in Sensor Configuration",
        "authors": "Ce Zhang; Dong Huang; Bao-Liang Lu",
        "year": "2019",
        "venue": "arXiv:1905.09472 / IEEE Transactions on Biomedical Engineering",
        "doi": "10.48550/arXiv.1905.09472",
        "url": "https://arxiv.org/abs/1905.09472v2",
        "local_path": "D:/ntk/eeg_paper_research/downloaded_papers/arxiv/[arXiv]_2019_EEG_Classification_by_factoring_in_Sensor_Configuration_1905.09472v2.pdf",
        "primary_cat": "H — Generalization / Domain Adaptation",
        "secondary_tags": "[EEG] [CHANNEL_INVARIANT] [CROSS_DATASET] [SPATIAL_INTERPOLATION] [SEED] [DEAP] [SUBJECT_INDEPENDENT]",
        "dataset": "SEED, DEAP",
        "modalities": "EEG (Variable channel montages: 14, 32, 62 channels)",
        "tasks": "Emotion Classification across Incompatible Electrode Montages",
        "arch": "Continuous Spherical Spline Spatial Interpolation + Invariant Neural Representation",
        "fusion": "Coordinate-Aware Spatial Embedding",
        "eval_proto": "Cross-Configuration & Cross-Dataset Transfer",
        "relevance": "Cross-dataset generalization, Sensor montage invariance, Geometry"
    }
]

print("Copying Batch 2 PDFs to literature/01_verified/...")
for p in papers_batch2:
    target_pdf_name = f"{p['id']}__{p['slug']}.pdf"
    target_pdf_path = os.path.join("literature/01_verified", target_pdf_name)
    src_path = p['local_path']
    if os.path.exists(src_path):
        shutil.copy2(src_path, target_pdf_path)
        print(f"[{p['id']}] Copied -> {target_pdf_name} ({os.path.getsize(target_pdf_path):,} bytes)")
    else:
        print(f"[{p['id']}] ERROR: Source not found: {src_path}")

print("PDF copy for Batch 2 complete.")
